[package]
name = "enum_dict"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Shigma <shigma10826@gmail.com>"]
description = ""
repository = "https://github.com/shigma/enum-dict"
documentation = "https://docs.rs/enum-dict"

